version: "3.9"

networks:
    maloinet:
                


services:
  mongo:
    image: mongo:4.4
    ports:
      - "27027:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./datadir:/data/db
    networks:
      - maloinet